### ISSUE TITLE
customize color and icons

### ISSUE THREAD

**Issue by antuki** [koncina/unilur#12]
Thank you for this very nice package that I used following the advice of @ginolhac
This package would be even better if it provided some customization features for the users such as
- customizing the colors of the defined block types (solution block in blue or green or any other color)
- allowing the addition of an icon before the title of the block (in the same logic as the advice and warning blocks).
I don’t know if these are some improvements that you would have in mind but you would make a  person happy!
… But that will not stop me from testing it anyway.
Thank you for this work!

**Comment by koncina** [comment]
Thank you very much for your feedback.

I'm thinking about a way to allow more customisation (without having to define the settings for the  each time for the same kind of boxes).
I will probably retain a box class definition (R function and/or setting in the yaml header as I used in the [IOSP package for the box colours](https://koncina.github.io/iosp/box_colours.html)).

It would then be easy to use different class names (such as warning, help...) to style different kind of boxes.

The settings could include:

- header background colour
- header text colour
- body background colour
- body text colour
- icon before header text
- collapsible settings

Overriding the colour(s) of the solution box should then also be possible...

I hope I will release it by the end of this month.

**Comment by antuki** [comment]
That would be great ! :)

**Comment by koncina** [comment]
Today is the promised due date. I pushed an updated version of unilur. I changed the chunk option arguments to customise the boxes and you can use the knitr option templates to create convenient shortcuts or override the appearance of solution boxes. Read [this article](http://koncina.github.io/unilur/articles/custom-boxes.html) to learn more about the usage.
I hope that everything is OK. As some breaking changes were introduced, I tagged the previous version (v0.4) allowing you to rollback if required.

**Comment by antuki** [comment]
Thank you Eric, I'm testing it right now and everything seems to work well. I'm customizing boxes and the result is great. I'm sure people would be seduced by your job. I'll try to do some advertising about it! Thanks again.

**Comment by antuki** [comment]
But i'm wondering:
the option ``solution_suffix: ""`` does not work with the master branch. Is it a conscious choice?
