### ISSUE TITLE
Is unilur working with html widgets ? 

### ISSUE THREAD

**Issue by antuki** [koncina/unilur#13]
Hello, it's me again.

I'm working on a cartography tutorial with unilur and I'm having problems with displaying interactive maps with the leaflet package. 
I wonder if there is a way to solve the problem easily? Do you think this issue concerns all html widgets? Thanks a lot for your help!

Working with html_document output

     ---
     title: "html_output"
     author: "antuki"
     output: html_document
     ---
     
     ```{r setup, include=FALSE}
     knitr::opts_chunk$set(echo = TRUE)
     ```
     
     ```{r}
     library(leaflet)
     leaflet() %>% addTiles()
     ```

Not working with unilur tutorial_html_solution output... : 

     ---
     title: "unilur_output"
     author: "antuki"
     output: 
       unilur::tutorial_html_solution
     ---
     
     ```{r setup, include=FALSE}
     knitr::opts_chunk$set(echo = TRUE)
     ```
     
     ```{r}
     library(leaflet)
     leaflet() %>% addTiles()
     ```

**Comment by antuki** [comment]
To be more precise, unilur creates this line in the html file : 

     <p>preservef6799606c3786201</p>


Instead of these ones :  

     <div id="htmlwidget-6d3ff75697902f18775d" style="width:672px;height:480px;" class="leaflet html-widget"></div>
     <script type="application/json" data-for="htmlwidget-6d3ff75697902f18775d">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"maxNativeZoom":null,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"continuousWorld":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":null,"unloadInvisibleTiles":null,"updateWhenIdle":null,"detectRetina":false,"reuseTiles":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]}]},"evals":[],"jsHooks":[]}</script>

**Comment by koncina** [comment]
Thank you for reporting this issue.
It seems that overriding the `post_processor()` disabled the `html_document` feature to handle widgets.

**Comment by antuki** [comment]
Super si la correction du bug n'était pas si compliquée !

Par contre, j'utilise la branche **dev** d'unilur car j'utilise les blocs warning et tips qui ne sont pas, il me semble, dans la branche **master** ? Est-ce qu'il y a une version qui cumule ces blocs et le bon fonctionnement des html widgets ? 
Merci.

**Comment by koncina** [comment]
I resolved the bug on the `dev` branch and merged it into the `master` branch (I just forgot to push the last commit to the github `dev` branch too: it is now online).

**Comment by antuki** [comment]
Thank you Eric, it is working perfectly well.
