### ISSUE TITLE
R code chunks not working for unilur:examen

### ISSUE THREAD

**Issue by SarahMuse** [koncina/unilur#14]
Writing R code chunks perfectly worked using unilur:tutorial. But, with unilur:examen, I have an error. See below:

`output:
  unilur::examen_pdf_solution:
    mcq: oneparcheckboxes
  unilur::examen_pdf:
    mcq: oneparcheckboxes
---

```{r}
mean(cars$speed)
````

> ! LaTeX Error: Command \framed already defined.
               Or name \end... illegal, see p.192 of the manual
> Error: Failed to compile 2_Central_Tendency_Exercises.tex. See 2_Central_Tendency_Exercises.log for more info.
> Execution halted

The thing is that I would like to use the mcq options from unilur:examen AND r chunks. As mcq options are not working for unilur:tutorial, I decided to use unilur:examen instead. But still, I have issues. Is it an issue with the unilur? Or a mistake from my side?

**Comment by ginolhac** [comment]
hello,

I cannot reproduce using latest the github unilur (koncina/unilur@c28888d). Just adding a R chunk with mean of `mtcars$mpg`

~~~
---
title: 'Title'
author: 'John Doe'
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  unilur::examen_pdf_solution:
    mcq: oneparcheckboxes
  unilur::examen_pdf:
    mcq: oneparcheckboxes
---

##### Multiple choice question

```{asis, mcq = TRUE}
- Item 1
- Item 2
- Item 3
```

##### Question

```{asis, solution = TRUE, response.space = 0.5}
This is the answer which is replaced by dotted lines in the question file!
```

```{r}
mean(mtcars$mpg)
```
~~~

gives:

<img width="404" alt="unilur" src="https://user-images.githubusercontent.com/710181/45776283-bf711700-bc52-11e8-80e6-49a766d1de4c.png">

which LateX engine are you using? I am using `tinytex` and it installed the `exam.cls` automatically.

**Comment by SarahMuse** [comment]
Hi!

Thank you for the answer! On my Linux and Mac machines, I am using Tex Live and I did check for the presence of the exam.cls file:

`kpsewhich exam.cls
/usr/share/texlive/texmf-dist/tex/latex/exam/exam.cls  #Linux
/usr/local/texlive/2017/texmf-dist/tex/latex/exam/exam.cls  #Mac`

Thus, I decided to update the Tex Live version of Mac on 2018 and it is working now. I will do the same for my Linux and see if it is working too. Thx for the help!
