### ISSUE TITLE
Inline R within block

### ISSUE THREAD

**Issue by Oromendia** [koncina/unilur#15]
Thanks for an amazing tool! 
I was wondering if it is possible to run inline r within a block chunk. My solutions often require interpretation of coefficients, and it would be nice to do "The coefficient is 'r mod$coef '. "

**Comment by koncina** [comment]
This is unfortunately a rmarkdown limitation as inline R codes nested within block code chunks are not evaluated.
A workaround would be to create a parent Rmd, write your solution chunks as child Rmd files and include them using `knitr::knit_child()`:

~~~
```{r, solution = TRUE, echo = FALSE, results = "asis"}
knitr::knit_child('child.Rmd', quiet = TRUE) %>% 
  glue::glue_collapse(sep = "\n")
```
~~~

You can have a look at an example in this [gist](https://gist.github.com/koncina/214801f59af2f744ae1035c5767c2c4f) with the [rendered output](https://cdn.rawgit.com/koncina/214801f59af2f744ae1035c5767c2c4f/raw/daba565c3d2a9ceadc5c4844749cadc3f426c71f/parent_solution.html).

**Comment by Oromendia** [comment]
I see. Thank you for the quick response and clear example.
