### ISSUE TITLE
copy icon in boxes

### ISSUE THREAD

**Issue by ginolhac** [koncina/unilur#18]
inspired from https://pkg.garrickadenbuie.com/xaringanExtra/#/clipboard

**Comment by koncina** [comment]
If I got your correctly you would like to include the feature to copy the source code from boxes... But this seems to work out of the box. According to [slide 6 of the demo](https://pkg.garrickadenbuie.com/xaringanExtra/clipboard/#6) it says it would work in Rmarkdown...
I did a quick test using coloured boxes and it seems to work as expected. So why don't you use the package as is at it seems compatible?

**Comment by ginolhac** [comment]
RTFM!!! :100: 
Works like a charm, thanks!
