### ISSUE TITLE
credit not working on mac

### ISSUE THREAD

**Issue by ginolhac** [koncina/unilur#3]

**Comment by ginolhac** [comment]
fixed with no header in 7022cc473ca387b7c7b301cf1f6db1a179848699

**Comment by koncina** [comment]
fix (which removes the running title in the header) is now in master branch [78369f8](https://github.com/koncina/unilur/commit/78369f85e2d976ee47da3482392e49757b227384).
I don't know the exact origin of the problem, either:
- Mactex does not like `\@title` macros (unlikely)
- The pandoc template used in Mac OS calls `\maketitle` earlier which will flush the `\@title` macro...

It should be possible to reintegrate running titles by using the [titling](http://ctan.org/pkg/titling) package. Don't know if it is useful.
