### ISSUE TITLE
html_output

### ISSUE THREAD

**Issue by ginolhac** [koncina/unilur#4]
With and without solutions

**Comment by koncina** [comment]
Commit [41f010f](https://github.com/koncina/unilur/commit/41f010f9c4aafb466783babf4c4153f66ac33366) in `dev` branch adds the possibility to render HTML files.
You need to replace the `unilur::tutorial` output by `unilur::tutorial_html` **and** remove the `unilur::knit()` call from the header.

**What works:**
- Solution chunks are hidden when solution is not `TRUE` (yes)
- Solution chunks are rendered in green boxes
- Box colors are partly supported (colors that work are listed in the R `colors()` function). I will update the main tutorial (pdf) and switch from latex xcolor dvipsnames to R `colors()` for better cross compatibility.

**What does not work:**
- As the `unilur::knit()` function needs to be removed from the yaml header:
  - It is not possible (yet) to render both HTML files in one click (with and without solutions)
  - The same output filename will be used for HTML with and without solutions
- No examen mode for HTML _but I will anyway split the tutorial format and create a new one for examen._

I'm trying to figure out how to manage both renderings more interactively. I don't know how (maybe it's not possible) to customize the rstudio button to propose different knittings (pdf, html).

Leaving the issue open as long as the proposed solution is not satisfactory.

**Comment by ginolhac** [comment]
great! would it be too much of an hassle to have the theme working?

```
unilur::tutorial_html:
    theme: cosmo
```

**Comment by koncina** [comment]
Should work with commit [3d43f9d](https://github.com/koncina/unilur/commit/3d43f9d88f20b831d29ccb0cfef6307e0bc045e0)

**Comment by ginolhac** [comment]
It does, thanks. Waiting for the rstudio next version you mentionned
https://github.com/rstudio/rstudio/blob/master/NEWS.md#r-markdown
