### ISSUE TITLE
avoid page breaks in code chunks

### ISSUE THREAD

**Issue by ginolhac** [koncina/unilur#6]
that would be nice to avoid this kind of page breaks:
![image](https://cloud.githubusercontent.com/assets/710181/16081964/1a93b01c-3310-11e6-8e5a-0632d4de34aa.png)

**Comment by ginolhac** [comment]
is it the option `samepage = TRUE` ?

**Comment by koncina** [comment]
The `samepage = TRUE` is a yet undocumented experimental R chunk option (in _unilur_) which is indeed avoiding pagebreaks within a chunk. However, it was actually only active on R outputs (and not inputs as in the example above). I enabled it for input chunks in commit [41fd9de](https://github.com/koncina/unilur/commit/41fd9de707dcc23a4bc3d7fa6c23a8c21dbd9f03) (still in the `dev` branch). Feel free to test the commit and close the issue if it's working as expected!

**Comment by ginolhac** [comment]
looks good! thanks

**Comment by koncina** [comment]
Commit [41fd9de](https://github.com/koncina/unilur/commit/41fd9de707dcc23a4bc3d7fa6c23a8c21dbd9f03) might not solve the problem as it only avoids a pagebreak within the latex `verbatim` and not in the `mdframed` environment. Try commit [c5e51f1](https://github.com/koncina/unilur/commit/c5e51f1d2649645f8c59cd8007a3815bef26f756) to completely avoid a pagebreak within the input chunk including its box.

**Comment by ginolhac** [comment]
be aware that I work with `examen_pdf` not `tutorial_pdf` so should be in both

**Comment by koncina** [comment]
Actually `examen_pdf` is inheriting and expanding `tutorial_pdf`, so it should work for both.
