### ISSUE TITLE
Including Tables

### ISSUE THREAD

**Issue by mgoplerud** [koncina/unilur#7]
Hi! I am using this package for a class that I'm teaching (it's great), but I can't seem to find a way to get tables from R to print in the PDF/LaTeX document.

The following runs fine:
```{r, echo = FALSE, results = "asis"}
print(xtable::xtable(data))
```

The following fails:
```{r, echo = FALSE, results = "asis", solution = TRUE}
print(xtable::xtable(data))
```
! LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
pandoc fails with error 43.
Any thoughts would be greatly appreciated!

**Comment by koncina** [comment]
Thank you for using `unilur`.

I presume the github markdown renderer removed the chunk options in your issue report and that you're not able to use `print(xtable::xtable(data))` with `solution = TRUE`.
This is in fact a limitation of the latex `mdframed` environment (used to draw the boxes) which will fail with nested floats (like `table` or `figure`).

For example, the code below will fail:
~~~
```{asis, solution = TRUE}
\begin{table}
\end{table}
```
~~~

The easiest way to produce tables in a solution chunk would be to use `knitr::kable()`. If you still would like to use `xtable::xtable()` you will have to remove the floating `table` environment in `print()`. You should also turn off the comment as the `%` character will not be recognized as a latex comment during knitting.

The following code should work:

~~~
```{r, solution = TRUE}
print(xtable::xtable(data), floating = FALSE, comment = FALSE)
```
~~~

**Comment by mgoplerud** [comment]
Perfect; than you so much. In case other people see this and are interested, I wrote the following small wrapper function to allow you to use "xtable" and "caption" (needs \usepackage{caption}) together.

```
solution.table <- function(object, caption = '', centering = TRUE, other.adding = ''){
  get.xtable.object <- print(xtable::xtable(object), floating = FALSE, print.results = FALSE, sanitize.colnames.function = function(x){x})
  if (is.null(caption)){
    caption.arg <- ''
  }else{
    caption.arg <- paste('\\captionof{table}{', caption, '}', sep = '')
  }
  if (centering){
    output <- paste('\\begin{center}\n', caption.arg, '\n', get.xtable.object, '\n', other.adding, '\\end{center}', sep = '')
  }else{
    output <- paste(caption.arg, '\n', get.xtable.object, '\n', other.adding, sep = '')
    
  }
  cat(output)
}
```
